name: Our love, Run away, Gotta save it.

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Like it never left.
    steps:
      - name: Fuck a version
        id: version
        shell: bash
        run: echo "version=$(date +%s)" >> "$GITHUB_OUTPUT"

      - name: Just build, Don't worry
        uses: moaeiou/moaeiou/actions/buildnode@main
        with:
          pnpm: no
          command: |
            npx --yes esbuild --minify --allow-overwrite --legal-comments=none fancyindex.js --outfile=./fancyindex.js
            npx --yes esbuild --minify --allow-overwrite --legal-comments=none style.css --outfile=./style.css
            curl -LO https://raw.githubusercontent.com/moaeiou/moaeiou/refs/heads/main/.github/workflows/format.js
            node format.js header.html ./header.html
            node format.js footer.html ./footer.html
            tar -cvf fi.tar.zst --zstd header.html footer.html style.css fancyindex.js
            ln -s ./fi.tar.zst ./0fi.tar.zst
          release: yes
          release-tag_name: ${{ steps.version.outputs.version }}
          release-files: 0fi.tar.zst
          rsync: "yes"
          rsync-local: fi.tar.zst
          rsync-key: ${{ secrets.SSH_KEY }}